# Error handlers
class CustomError(Exception):
    pass
